# ==========================================
# gestion de energia, creo que lo hace automaticamente
# ==========================================
CONFIG_PM_DEVICE=y
CONFIG_SYS_CLOCK_EXISTS=y

# ==========================================
# PERIFÉRICOS
# ==========================================
CONFIG_NRFX_GPPI=y
CONFIG_NRFX_RTC=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_ADC=y

# ==========================================
# BLUETOOTH Y SINCRONIZACIÓN DE HORA (CTS)
# ==========================================
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_CTS_CLIENT=y        #habilita el cliente del Current Time Service 
CONFIG_BT_ANCS_CLIENT=y
CONFIG_BT_AMS_CLIENT=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_DM=y

# ==========================================
# SEGURIDAD BLUETOOTH Y GUARDADO DE EMPAREJAMIENTO (Vital para ANCS)
# ==========================================
CONFIG_BT_SMP=y                 # Security Manager Protocol (Para poder emparejar)
CONFIG_BT_SETTINGS=y            # Permite guardar los emparejamientos
CONFIG_FLASH=y                  # Activa la memoria Flash
CONFIG_NVS=y                    # Non-Volatile Storage (Sistema de archivos ligero)
CONFIG_SETTINGS=y               # Subsistema de configuraciones de Zephyr


#aumento la memoria max de los mensajes
CONFIG_BT_L2CAP_TX_MTU=247
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251

#mayores retrasos para mejor bateria
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y
# 400 ms
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=320
# 500 ms
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=400
# 3 ciclos (1.5 segundos efectivos)
CONFIG_BT_PERIPHERAL_PREF_LATENCY=2
# 5.5 segundos. Cumple: 5.5s > (1.5s * 3), necesario para apple
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=550    

# ==========================================
# GESTIÓN DE FECHA Y HORA
# ==========================================
# CONFIG_DATE_TIME=y
# CONFIG_DATE_TIME_NTP=n

# ==========================================
# SISTEMA DE PANTALLA Y LVGL (monocromatico)
# ==========================================
CONFIG_DISPLAY=y
CONFIG_LVGL=y
CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_VDB_SIZE=100
CONFIG_LV_Z_FULL_REFRESH=y #refresco todo porque ocupa poco, quizas es hasta peor ir por cachos solo (no estoy seguro)
CONFIG_LV_Z_MEM_POOL_SIZE=8192

#para que haya un hilo de LVGL independiente
#CONFIG_LV_Z_K_THREAD
#CONFIG_LV_Z_K_THREAD_PRIO


# ==========================================
# depuracion (envolver en #ifdef cuando lo desactive)
# ==========================================
# Sistema de Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y #para que se guarde en buffer y no se pierda nada, confio en que no pete demasiado
#CONFIG_LOG_MODE_IMMEDIATE=y #para que sea inmediato y no se quede en buffer

#habilitar consola serie
CONFIG_SERIAL=y         # controla UART y eso, poner a n en produccion
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

#activar usb y cdc acm
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y
