# Disable hardware-specific systems
CONFIG_BT=n
CONFIG_ADC=n
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_USBD_CDC_ACM_CLASS=n

# Enable SDL Display for LVGL UI testing
CONFIG_DISPLAY=y
CONFIG_SDL_DISPLAY=y
CONFIG_LV_Z_FLUSH_THREAD=y

# Standard UART console so your keyboard polling works in the terminal
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y